(ns starkinfra.issuing-holder
  "The IssuingHolder describes a card holder that may group several cards.

  ## Parameters (required):
    - `:name` [string]: card holder name. ex: \"Tony Stark\"
    - `:tax-id` [string]: card holder tax ID ex: \"012.345.678-90\"
    - `:external-id` [string]: card holder unique id, generated by the user to avoid duplicated holders. ex: \"my-entity/123\"

  ## Parameters (optional):
    - `:rules` [list of maps, default []]: [EXPANDABLE] list of holder spending rules. See `starkinfra.issuing-rule` for the map shape.
    - `:tags` [list of strings, default []]: list of strings for tagging. ex: [\"travel\", \"food\"]

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when IssuingHolder is created. ex: \"5656565656565656\"
    - `:status` [string]: current IssuingHolder status. ex: \"active\", \"blocked\", \"canceled\"
    - `:created` [string]: creation datetime for the IssuingHolder. ex: \"2020-03-10T10:30:00.000000+00:00\"
    - `:updated` [string]: latest update datetime for the IssuingHolder. ex: \"2020-03-10T10:30:00.000000+00:00\""
  (:refer-clojure :exclude [get update])
  (:require [starkinfra.settings :refer [credentials]]
            [starkinfra.utils.rest :refer [delete-id get-id get-page get-stream
                                           patch-id post-multi]]))

(defn- resource []
  "issuing-holder")


(defn create
  "Send a list of IssuingHolder maps for creation at the Stark Infra API.

  ## Parameters (required):
    - `holders` [list of maps]: list of IssuingHolder maps to be created in the API. You can send up to 100 IssuingHolder maps in a single request.

  ## Parameters (optional):
    - `params` [map]:
      - `:expand` [list of strings, default nil]: fields to expand information. Options: [\"rules\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - list of IssuingHolder maps with updated attributes"
  ([holders]
   (post-multi @credentials (resource) holders {}))

  ([holders params]
   (post-multi @credentials (resource) holders params))

  ([holders params user]
   (post-multi user (resource) holders params)))

(defn get
  "Receive a single IssuingHolder map previously created in the Stark Infra API by its id.

  ## Parameters (required):
    - `id` [string]: map unique id. ex: \"5656565656565656\"

  ## Parameters (optional):
    - `params` [map]:
      - `:expand` [list of strings, default nil]: fields to expand information. Options: [\"rules\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - IssuingHolder map with updated attributes"
  ([id]
   (get-id @credentials (resource) id {}))

  ([id params]
   (get-id @credentials (resource) id params))

  ([id params user]
   (get-id user (resource) id params)))

(defn query
  "Receive a stream of IssuingHolder maps previously created in the Stark Infra API.

  ## Options:
    - `:limit` [integer, default nil]: maximum number of maps to be retrieved. Unlimited if nil. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-03-10\"
    - `:status` [list of strings, default nil]: filter for status of retrieved maps. ex: [\"active\", \"blocked\", \"canceled\"]
    - `:tags` [list of strings, default nil]: tags to filter retrieved maps. ex: [\"tony\", \"stark\"]
    - `:expand` [string, default nil]: fields to expand information. Options: [\"rules\"]
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - stream of IssuingHolder maps with updated attributes"
  ([]
   (get-stream @credentials (resource) {}))

  ([params]
   (get-stream @credentials (resource) params))

  ([params user]
   (get-stream user (resource) params)))

(defn page
  "Receive a list of up to 100 IssuingHolder maps previously created in the Stark Infra API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default 100]: maximum number of maps to be retrieved. Max = 100. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-03-10\"
    - `:status` [list of strings, default nil]: filter for status of retrieved maps. ex: [\"active\", \"blocked\", \"canceled\"]
    - `:tags` [list of strings, default nil]: tags to filter retrieved maps. ex: [\"tony\", \"stark\"]
    - `:expand` [string, default nil]: fields to expand information. Options: [\"rules\"]
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - map with `:content` and `:cursor`:
      - `:content`: list of IssuingHolder maps with updated attributes
      - `:cursor`: cursor string to retrieve the next page, empty when there is none"
  ([]
   (get-page @credentials (resource) {}))

  ([params]
   (get-page @credentials (resource) params))

  ([params user]
   (get-page user (resource) params)))

(defn update
  "Update an IssuingHolder by passing id, if it hasn't been paid yet.

  ## Parameters (required):
    - `id` [string]: IssuingHolder id. ex: \"5656565656565656\"

  ## Parameters (optional):
    - `params` [map]:
      - `:status` [string]: You may block the IssuingHolder by passing 'blocked' in the status
      - `:name` [string]: card holder name. ex: \"Tony Stark\"
      - `:tags` [list of strings]: list of strings for tagging. ex: [\"tony\", \"stark\"]
      - `:rules` [list of maps, default nil]: list of maps with \"amount\": int, \"currencyCode\": string, \"id\": string, \"interval\": string, \"name\": string pairs
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - target IssuingHolder with updated attributes"
  ([id params]
   (patch-id @credentials (resource) params id))

  ([id params user]
   (patch-id user (resource) params id)))

(defn cancel
  "Cancel an IssuingHolder entity previously created in the Stark Infra API.

  ## Parameters (required):
    - `id` [string]: IssuingHolder unique id. ex: \"5656565656565656\"

  ## Parameters (optional):
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - canceled IssuingHolder map"
  ([id]
   (delete-id @credentials (resource) id {}))

  ([id user]
   (delete-id user (resource) id {})))
