(ns starkinfra.issuing-balance
  "The IssuingBalance map displays the current issuing balance of the
  Workspace, which is the result of the sum of all transactions within this
  Workspace. The balance is never generated by the user, but it can be
  retrieved to see the available information.

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when IssuingBalance is created. ex: \"5656565656565656\"
    - `:amount` [integer]: current balance amount of the Workspace in cents. ex: 200 (= R$ 2.00)
    - `:currency` [string]: currency of the current Workspace. Expect others to be added eventually. ex: \"BRL\"
    - `:limit` [integer]: spending limit of the balance
    - `:max-limit` [integer]: maximum spending limit. This field is currently always equal to limit
    - `:updated` [string]: latest update datetime for the IssuingBalance. ex: \"2020-03-10T10:30:00.000000+00:00\""
  (:refer-clojure :exclude [get])
  (:require [starkinfra.settings :refer [credentials]]
            [starkinfra.utils.rest :refer [get-stream]]))

(defn- resource []
  "issuing-balance")


(defn get
  "Receive the IssuingBalance map linked to your Workspace in the Stark Infra API.

  ## Parameters (optional):
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - IssuingBalance map with updated attributes"
  ([]
   (first (get-stream @credentials (resource) {})))

  ([user]
   (first (get-stream user (resource) {}))))
