(ns starkinfra.issuing-card
  "The IssuingCard map displays the information of the cards created in your
  Workspace. Sensitive information will only be returned when the \"expand\"
  parameter is used, to avoid security concerns.

  ## Parameters (required):
    - `:holder-name` [string]: card holder name. ex: \"Tony Stark\"
    - `:holder-tax-id` [string]: card holder tax ID. ex: \"012.345.678-90\"
    - `:holder-external-id` [string]: card holder unique id, generated by the user to avoid duplicated holders. ex: \"my-entity/123\"

  ## Parameters (optional):
    - `:type` [string, default \"virtual\"]: card type. Options: \"virtual\", \"physical\" (physical cards require embossing and shipping).
    - `:display-name` [string, default nil]: card displayed name. ex: \"ANTHONY STARK\"
    - `:rules` [list of maps, default []]: [EXPANDABLE] list of card spending rules. See `starkinfra.issuing-rule` for the map shape.
    - `:product-id` [string, default nil]: card product ID to which the card is bound. ex: \"53810200\"
    - `:tags` [list of strings, default []]: list of strings for tagging. ex: [\"travel\", \"food\"]
    - `:street-line-1` [string, default sub-issuer street line 1]: card holder main address. ex: \"Av. Paulista, 200\"
    - `:street-line-2` [string, default sub-issuer street line 2]: card holder address complement. ex: \"Apto. 123\"
    - `:district` [string, default sub-issuer district]: card holder address district / neighbourhood. ex: \"Bela Vista\"
    - `:city` [string, default sub-issuer city]: card holder address city. ex: \"Rio de Janeiro\"
    - `:state-code` [string, default sub-issuer state code]: card holder address state. ex: \"GO\"
    - `:zip-code` [string, default sub-issuer zip code]: card holder address zip code. ex: \"01311-200\"

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when IssuingCard is created. ex: \"5656565656565656\"
    - `:holder-id` [string]: card holder unique id. ex: \"5656565656565656\"
    - `:type` [string]: card type. ex: \"virtual\"
    - `:status` [string]: current IssuingCard status. ex: \"active\", \"blocked\", \"canceled\", \"expired\"
    - `:is-pin-defined` [bool]: Whether the card has a PIN defined. Returned only when \"expand=isPinDefined\" is informed in the request
    - `:number` [string]: [EXPANDABLE] masked card number. Expand to unmask the value. ex: \"123\"
    - `:security-code` [string]: [EXPANDABLE] masked card verification value (cvv). Expand to unmask the value. ex: \"123\"
    - `:expiration` [string]: [EXPANDABLE] masked card expiration datetime. Expand to unmask the value. ex: \"2020-03-10T10:30:00.000000+00:00\"
    - `:updated` [string]: latest update datetime for the IssuingCard. ex: \"2020-03-10T10:30:00.000000+00:00\"
    - `:created` [string]: creation datetime for the IssuingCard. ex: \"2020-03-10T10:30:00.000000+00:00\""
  (:refer-clojure :exclude [get update])
  (:require [starkinfra.settings :refer [credentials]]
            [starkinfra.utils.rest :refer [delete-id get-id get-page get-stream
                                           patch-id post-multi]]))

(defn- resource []
  "issuing-card")


(defn create
  "Send a list of IssuingCard maps for creation at the Stark Infra API.

  ## Parameters (required):
    - `cards` [list of maps]: list of IssuingCard maps to be created in the API. You can send up to 100 IssuingCard maps in a single request.

  ## Parameters (optional):
    - `params` [map]:
      - `:expand` [list of strings, default nil]: fields to expand information. Options: \"rules\", \"security_code\", \"number\", \"expiration\", \"is_pin_defined\"
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - list of IssuingCard maps with updated attributes"
  ([cards]
   (post-multi @credentials (resource) cards {}))

  ([cards params]
   (post-multi @credentials (resource) cards params))

  ([cards params user]
   (post-multi user (resource) cards params)))

(defn query
  "Receive a stream of IssuingCard maps previously created in the Stark Infra API.

  ## Options:
    - `:limit` [integer, default nil]: maximum number of maps to be retrieved. Unlimited if nil. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-03-10\"
    - `:status` [list of strings, default nil]: filter for status of retrieved maps. ex: [\"active\", \"blocked\", \"canceled\", \"expired\"]
    - `:types` [list of strings, default nil]: card type. ex: [\"virtual\"]
    - `:holder-ids` [list of strings]: card holder IDs. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:tags` [list of strings, default nil]: tags to filter retrieved maps. ex: [\"tony\", \"stark\"]
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:expand` [list of strings, default nil]: fields to expand information. ex: [\"rules\", \"security_code\", \"number\", \"expiration\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - stream of IssuingCard maps with updated attributes"
  ([]
   (get-stream @credentials (resource) {}))

  ([params]
   (get-stream @credentials (resource) params))

  ([params user]
   (get-stream user (resource) params)))

(defn page
  "Receive a list of up to 100 IssuingCard maps previously created in the Stark Infra API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default 100]: maximum number of maps to be retrieved. Max = 100. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-03-10\"
    - `:status` [list of strings, default nil]: filter for status of retrieved maps. ex: [\"active\", \"blocked\", \"canceled\", \"expired\"]
    - `:types` [list of strings, default nil]: card type. ex: [\"virtual\"]
    - `:holder-ids` [list of strings]: card holder IDs. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:tags` [list of strings, default nil]: tags to filter retrieved maps. ex: [\"tony\", \"stark\"]
    - `:expand` [list of strings, default nil]: fields to expand information. ex: [\"rules\", \"security_code\", \"number\", \"expiration\"]
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - map with `:content` and `:cursor`:
      - `:content`: list of IssuingCard maps with updated attributes
      - `:cursor`: cursor string to retrieve the next page, empty when there is none"
  ([]
   (get-page @credentials (resource) {}))

  ([params]
   (get-page @credentials (resource) params))

  ([params user]
   (get-page user (resource) params)))

(defn get
  "Receive a single IssuingCard map previously created in the Stark Infra API by its id.

  ## Parameters (required):
    - `id` [string]: map unique id. ex: \"5656565656565656\"

  ## Parameters (optional):
    - `params` [map]:
      - `:expand` [list of strings, default nil]: fields to expand information. ex: [\"rules\", \"security_code\", \"number\", \"expiration\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - IssuingCard map with updated attributes"
  ([id]
   (get-id @credentials (resource) id {}))

  ([id params]
   (get-id @credentials (resource) id params))

  ([id params user]
   (get-id user (resource) id params)))

(defn update
  "Update an IssuingCard by passing id.

  ## Parameters (required):
    - `id` [string]: IssuingCard id. ex: \"5656565656565656\"

  ## Parameters (optional):
    - `params` [map]:
      - `:status` [string, default nil]: You may block the IssuingCard by passing 'blocked' or activate by passing 'active' in the status
      - `:pin` [string, default nil]: You may unlock your physical card by passing its PIN. This is also the PIN you use to authorize a purhcase.
      - `:display-name` [string, default nil]: card displayed name. ex: \"ANTHONY EDWARD\"
      - `:rules` [list of maps, default nil]: list of maps with \"amount\": int, \"currencyCode\": string, \"id\": string, \"interval\": string, \"name\": string pairs.
      - `:tags` [list of strings, default nil]: list of strings for tagging
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - target IssuingCard with updated attributes"
  ([id params]
   (patch-id @credentials (resource) params id))

  ([id params user]
   (patch-id user (resource) params id)))

(defn cancel
  "Cancel an IssuingCard entity previously created in the Stark Infra API.

  ## Parameters (required):
    - `id` [string]: IssuingCard unique id. ex: \"5656565656565656\"

  ## Parameters (optional):
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - canceled IssuingCard map"
  ([id]
   (delete-id @credentials (resource) id {}))

  ([id user]
   (delete-id user (resource) id {})))
