(ns starkinfra.issuing-billing-transaction
  "Check out our API Documentation at https://starkinfra.com/docs/api#issuing-billing-transaction

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when IssuingBillingTransaction is created. ex: \"5656565656565656\"
    - `:amount` [integer]: IssuingBillingTransaction value in cents. Positive for credits, negative for debits. ex: 1234 (= R$ 12.34) or -1234 for a debit.
    - `:invoice-id` [string]: unique id of the IssuingBillingInvoice that generated this transaction. ex: \"5656565656565656\"
    - `:installment` [integer]: installment number of the IssuingBillingInvoice payment this transaction refers to. ex: 1
    - `:installment-count` [integer]: total number of installments of the IssuingBillingInvoice payment. ex: 3
    - `:balance` [integer]: balance amount of the Workspace at the instant of the transaction in cents. ex: 200 (= R$ 2.00)
    - `:holder-name` [string]: cardholder name linked to the transaction, when applicable. ex: \"Tony Stark\"
    - `:source` [string]: source of the transaction. ex: \"issuing-billing-invoice/5656565656565656\"
    - `:external-id` [string]: unique id, generated by user, to avoid duplicated transactions. ex: \"my-unique-id-123\"
    - `:description` [string]: IssuingBillingTransaction description. ex: \"Issuing invoice installment payment\"
    - `:card-ending` [string]: last 4 digits of the card used in the transaction, when applicable. ex: \"1234\"
    - `:tax` [integer]: IOF amount in cents applied to the transaction
    - `:rate` [float]: conversion rate applied to international transactions
    - `:merchant-amount` [integer]: amount charged by the merchant, in the merchant currency, when applicable. ex: 1000
    - `:merchant-currency-code` [string]: currency in which the merchant amount was charged. ex: \"USD\"
    - `:created` [string]: creation datetime for the IssuingBillingTransaction. ex: \"2020-03-10T10:30:00.000000+00:00\""
  (:require [starkinfra.settings :refer [credentials]]
            [starkinfra.utils.rest :refer [get-page get-stream]]))

(defn- resource []
  "issuing-billing-transaction")


(defn query
  "Receive a stream of IssuingBillingTransaction maps previously created in the Stark Infra API.
  Check out our API Documentation at https://starkinfra.com/docs/api#issuing-billing-transaction

  ## Options:
    - `:limit` [integer, default nil]: maximum number of maps to be retrieved. Unlimited if nil. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-03-10\"
    - `:invoice-id` [string, default nil]: filter for transactions generated by a specific IssuingBillingInvoice. ex: \"5656565656565656\"
    - `:tags` [list of strings, default nil]: tags to filter retrieved maps. ex: [\"tony\", \"stark\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - stream of IssuingBillingTransaction maps with updated attributes"
  ([]
   (get-stream @credentials (resource) {}))

  ([params]
   (get-stream @credentials (resource) params))

  ([params user]
   (get-stream user (resource) params)))

(defn page
  "Receive a list of IssuingBillingTransaction maps previously created in the Stark Infra API and the cursor to the next page.
  Check out our API Documentation at https://starkinfra.com/docs/api#issuing-billing-transaction

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default 100]: maximum number of maps to be retrieved. Max = 100. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-03-10\"
    - `:invoice-id` [string, default nil]: filter for transactions generated by a specific IssuingBillingInvoice. ex: \"5656565656565656\"
    - `:tags` [list of strings, default nil]: tags to filter retrieved maps. ex: [\"tony\", \"stark\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - map with `:content` and `:cursor`:
      - `:content`: list of IssuingBillingTransaction maps with updated attributes
      - `:cursor`: cursor string to retrieve the next page, empty when there is none"
  ([]
   (get-page @credentials (resource) {}))

  ([params]
   (get-page @credentials (resource) params))

  ([params user]
   (get-page user (resource) params)))
