(ns starkinfra.issuing-purchase.log
  "Every time an IssuingPurchase entity is updated, a corresponding
  issuing-purchase.Log is generated for the entity. This log is never
  generated by the user, but it can be retrieved to check additional
  information on the IssuingPurchase.

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when the log is created. ex: \"5656565656565656\"
    - `:purchase` [map]: IssuingPurchase entity to which the log refers to.
    - `:installment` [integer]: number of the installment that is being confirmed.
    - `:issuing-transaction-id` [string]: transaction ID related to the IssuingCard.
    - `:errors` [list of strings]: list of errors linked to this IssuingPurchase event.
    - `:type` [string]: type of the IssuingPurchase event which triggered the log creation. ex: \"approved\", \"canceled\", \"confirmed\", \"denied\", \"reversed\", \"voided\"
    - `:created` [string]: creation datetime for the log. ex: \"2020-03-10T10:30:00.000000+00:00\""
  (:refer-clojure :exclude [get])
  (:require [starkinfra.settings :refer [credentials]]
            [starkinfra.utils.rest :refer [get-id get-page get-stream]]))

(defn- resource []
  "issuing-purchase-log")


(defn get
  "Receive a single issuing-purchase.Log map previously created by the Stark Infra API by its id.

  ## Parameters (required):
    - `id` [string]: map unique id. ex: \"5656565656565656\"

  ## Parameters (optional):
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - issuing-purchase.Log map with updated attributes"
  ([id]
   (get-id @credentials (resource) id {}))

  ([id user]
   (get-id user (resource) id {})))

(defn query
  "Receive a stream of issuing-purchase.Log maps previously created in the Stark Infra API.

  ## Options:
    - `:ids` [list of strings, default nil]: list of IssuingPurchase ids to filter logs. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:limit` [integer, default nil]: maximum number of maps to be retrieved. Unlimited if nil. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-03-10\"
    - `:types` [list of strings, default nil]: filter for log event types. ex: [\"approved\", \"canceled\", \"confirmed\", \"denied\", \"reversed\", \"voided\"]
    - `:purchase-ids` [list of strings, default nil]: list of Purchase ids to filter logs. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - stream of issuing-purchase.Log maps with updated attributes"
  ([]
   (get-stream @credentials (resource) {}))

  ([params]
   (get-stream @credentials (resource) params))

  ([params user]
   (get-stream user (resource) params)))

(defn page
  "Receive a list of up to 100 issuing-purchase.Log maps previously created in the Stark Infra API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:ids` [list of strings, default nil]: list of IssuingPurchase ids to filter logs. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `:limit` [integer, default 100]: maximum number of maps to be retrieved. Max = 100. ex: 35
    - `:after` [string, default nil]: date filter for maps created only after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created only before specified date. ex: \"2020-03-10\"
    - `:types` [list of strings, default nil]: filter for log event types. ex: [\"approved\", \"canceled\", \"confirmed\", \"denied\", \"reversed\", \"voided\"]
    - `:purchase-ids` [list of strings, default nil]: list of Purchase ids to filter logs. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - map with `:content` and `:cursor`:
      - `:content`: list of issuing-purchase.Log maps with updated attributes
      - `:cursor`: cursor string to retrieve the next page, empty when there is none"
  ([]
   (get-page @credentials (resource) {}))

  ([params]
   (get-page @credentials (resource) params))

  ([params user]
   (get-page user (resource) params)))
