(ns starkinfra.pix-reversal.log
  "Every time a PixReversal entity is modified, a corresponding PixReversal.Log
  is generated for the entity. This log is never generated by the user.

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when the log is created. ex: \"5656565656565656\"
    - `:reversal` [map]: PixReversal entity to which the log refers to.
    - `:type` [string]: type of the PixReversal event which triggered the log creation. ex: \"sent\", \"denied\", \"failed\", \"created\", \"success\", \"approved\", \"credited\", \"refunded\", \"processing\"
    - `:errors` [list of strings]: list of errors linked to this PixReversal event
    - `:created` [string]: creation datetime for the log. ex: \"2020-03-10T10:30:00.000000+00:00\""
  (:refer-clojure :exclude [get])
  (:require [starkinfra.settings :refer [credentials]]
            [starkinfra.utils.rest :refer [get-id get-page get-stream]]))

(defn- resource []
  "pix-reversal-log")


(defn get
  "Receive a single PixReversal.Log map previously created by the Stark Infra API by its id.

  ## Parameters (required):
    - `id` [string]: map unique id. ex: \"5656565656565656\"

  ## Parameters (optional):
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - PixReversal.Log map with updated attributes"
  ([id]
   (get-id @credentials (resource) id {}))

  ([id user]
   (get-id user (resource) id {})))

(defn query
  "Receive a stream of PixReversal.Log maps previously created in the Stark Infra API.

  ## Options:
    - `:limit` [integer, default nil]: maximum number of maps to be retrieved. Unlimited if nil. ex: 35
    - `:after` [string, default nil]: date filter for maps created after specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created before a specified date. ex: \"2020-03-10\"
    - `:types` [list of strings, default nil]: filter retrieved maps by types. Options: [\"sent\", \"denied\", \"failed\", \"created\", \"success\", \"approved\", \"credited\", \"refunded\", \"processing\"]
    - `:reversal-ids` [list of strings, default nil]: list of PixReversal ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - stream of PixReversal.Log maps with updated attributes"
  ([]
   (get-stream @credentials (resource) {}))

  ([params]
   (get-stream @credentials (resource) params))

  ([params user]
   (get-stream user (resource) params)))

(defn page
  "Receive a list of up to 100 PixReversal.Log maps previously created in the Stark Infra API and the cursor to the next page.
  Use this function instead of query if you want to manually page your reversals.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default 100]: maximum number of maps to be retrieved. Max = 100. ex: 35
    - `:after` [string, default nil]: date filter for maps created after a specified date. ex: \"2020-03-10\"
    - `:before` [string, default nil]: date filter for maps created before a specified date. ex: \"2020-03-10\"
    - `:types` [list of strings, default nil]: filter retrieved maps by types. Options: [\"sent\", \"denied\", \"failed\", \"created\", \"success\", \"approved\", \"credited\", \"refunded\", \"processing\"]
    - `:reversal-ids` [list of strings, default nil]: list of PixReversal ids to filter retrieved maps. ex: [\"5656565656565656\", \"4545454545454545\"]
    - `user` [map, default nil]: Project or Organization map returned from starkinfra.user/project or starkinfra.user/organization. Only necessary if starkinfra.settings/user has not been set.

  ## Return:
    - map with `:content` and `:cursor`:
      - `:content`: list of PixReversal.Log maps with updated attributes
      - `:cursor`: cursor string to retrieve the next page of PixRequest.Log maps"
  ([]
   (get-page @credentials (resource) {}))

  ([params]
   (get-page @credentials (resource) params))

  ([params user]
   (get-page user (resource) params)))
